#This was removed from settings.json
from turtle import *
turtle = Turtle()
screen = Screen()
turtle.shape("turtle")
screen.listen()
screen.bgcolor("light blue")

turtle.penup()
turtle.goto(-60,100)
turtle.pendown()
turtle.hideturtle()

turtle.write("Welcome to the Maze game")
time.sleep(3)
turtle.clear()
turtle.write("Rules:")
turtle.penup()
turtle.backward(20)
turtle.right(90)
turtle.forward(10)
turtle.left(90) 
turtle.pendown()
turtle.write("Use arrow keys to move")
turtle.penup()
turtle.backward(20)
turtle.right(90)
turtle.forward(10)
turtle.left(90) 
turtle.pendown()
turtle.write("stay inside the lines and get to the end")
time.sleep(5)
turtle.clear()

turtle = Turtle()
turtle.shape("turtle")
turtle.speed(100)

turtle.penup()
turtle.goto(-80,60)
turtle.pendown()

turtle.left(90)
turtle.forward(80)
turtle.right(90)
turtle.forward(240)
turtle.right(90)
turtle.forward(200)
turtle.penup()
turtle.forward(40)
turtle.pendown()
turtle.right(90)
turtle.forward(240)
turtle.right(90)
turtle.forward(130)
turtle.penup()
turtle.forward(40)
turtle.pendown()
turtle.forward(20)
turtle.right(90)
turtle.forward(20)
turtle.right(90)
turtle.forward(60)
turtle.penup()
turtle.forward(35)
turtle.right(90)
turtle.forward(20)
turtle.left(180)
turtle.forward(30)
turtle.pendown()
turtle.forward(25)
turtle.left(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(10)
turtle.right(90)
turtle.forward(80)
turtle.right(90)
turtle.forward(20)
turtle.left(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(130)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(55)
turtle.left(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(30)
turtle.backward(60)
turtle.left(90)
turtle.forward(65)
turtle.penup()
turtle.forward(20)
turtle.pendown()
turtle.right(90)
turtle.forward(120)
turtle.right(90)
turtle.forward(135)
turtle.right(90)
turtle.forward(200)
turtle.right(90)
turtle.forward(90)
turtle.left(90)
turtle.forward(10)
turtle.left(180)
turtle.penup()
turtle.forward(30)
turtle.pendown()
turtle.right(90)
turtle.forward(70)
turtle.left(90)
turtle.forward(155)
turtle.left(90)
turtle.forward(95)
turtle.left(90)
turtle.forward(95)
turtle.right(90)

turtle.penup()
turtle.forward(20)
turtle.pendown()
turtle.forward(70)
turtle.left(90)
turtle.penup()
turtle.forward(20)
turtle.pendown()
turtle.forward(50)
turtle.right(90)
turtle.forward(20)
turtle.right(90)
turtle.forward(200)
turtle.right(90)
turtle.forward(20)
turtle.right(90)
turtle.forward(90)
turtle.left(90)
turtle.forward(20)
turtle.left(90)
turtle.forward(105)
turtle.right(90)
turtle.forward(150)
turtle.left(90)
turtle.forward(5)
turtle.right(90)
turtle.penup()
turtle.forward(40)
turtle.pendown()
turtle.right(90)
turtle.forward(25)
turtle.right(90)
turtle.forward(170)
turtle.left(90)
turtle.forward(85)
turtle.left(90)
turtle.forward(30)

turtle.penup()
turtle.forward(10)
turtle.right(90)
turtle.forward(110)
turtle.pendown()
turtle.backward(10)
turtle.right(90)
turtle.forward(40)
turtle.right(90)
turtle.forward(40)
turtle.left(90)
turtle.forward(40)

turtle.hideturtle()

screen.listen()

def forward():
  turtle.penup()
  turtle.forward(10)
  turtle.pendown()
screen.onkey(forward,"up")

def left():
  turtle.penup()
  turtle.left(90)
  turtle.pendown()
screen.onkey(left,"left")

def right():
  turtle.penup()
  turtle.right(90)
  turtle.pendown()
screen.onkey(right,"right")

turtle = Turtle()
turtle.shape("turtle")
turtle.penup()
turtle.goto(-90,45)